---
- name: build automatic remediation demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: build with ansible-builder
      shell:
        cmd: ansible-builder build --tag quay.io/bthomass/events-demo-ci-cd:latest --container-runtime docker
    - name: push to quay
      shell:
        cmd: docker push quay.io/bthomass/events-demo-ci-cd:latest
...
